---
title: "README"
author: "Simon J Brandl"
date: "05/04/2020"
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 1
---

The materials in this folder permit the reproduction of the results presented in Brandl et al. "Metabolic differentiation facilitates coexistence in two coral reef fish species." The code is written in the drake pipeline (https://github.com/ropensci/drake). The elements of the project (gobies_metabolism.Rproj) include: 

1) data: this folder includes all the raw data necessary to run the script.
2) output: this folder includesall outputs from the R-script.
3) documents: this folder includes the manuscript, appendices, and cover letter.
4) r: this folder contains three .R files, "packages.R", "functions.R", and "plan.R". To run the code for the entire project, simply open all three R files along with the _drake.R file. Make sure you have the drake package loaded in your environment and then run "r_make()" in your R console. For any issues, please do not hesitate to contact me. 

Datasets: a short description of each dataset is provided below.

# 1. commdat = Community data: data were collected using enclosed clove-oil stations in both the lagoon and on the forereef around the island of Mo'orea, French Polynesia. Contains each caught individual of cryptobenthic fish (as rows), including the two target species. Columns specify each individuals corresponding sampling information (location, site, outcrop, lat & long, curved surface length, depth), identity, size, etc. All collections done in 2017, 2018, 2019, and 2020.

# 2. respodat = Respirometry: these data are derived from intermittent respirometry, performed in the lab at CRIOBE. Each row is an individual fish and its associated metadata. SMR = standard metabolic rate in mg O2 per h. MaxMR = maximum metabolic rate in mg O2 per h. MeanTemp...C. = temperature in ºCelsius. Weight..kg. = mass in g.

# 3. morpho = External morphology; gut.morpho = internal morphology: data derived from measurements performed on individuals collected from the field. Two different datasets for external and internal morphology. Each row is a unique individual with associated metadata and measurements for SL (mm), TL (mm), weight (g), girth (mm), vertical gape size (V_gape, mm), and horizontal gape size (H_gape, mm). Gut morpho is a smaller set but same setup, with the length of the gastrointestinal tract (GIT) in mm.

# 4. DNA gut content metabarcoding, three distinct datasets:
#     a) gobies.meta = Metadata
#     b) gobies.coi = COI primer data
#     c) goby.23s = 23S primer data

# gobies.meta contains information on all sampled and processed individuals, with each individual havign a unique ID and its own row. IDs are critical to match with the two other datasets. 

# gobies coi and 23S: each row is an exact sequence variant (ESV) that was assigned to a prey taxon. Since this was part of a greater collection effort, there are many rows that are 0 across all columns. Columns 1:10 contain infromation about the sequence, while the remaining columns (G01 - G40) are individual fishes linked to the Extraction ID in the metadata. Values in the dataset are sequence abundances.

# 5. aquarium.trials = Feeding trials: data are observations from videos of sand gobies in varying configurations in aquaria. id = identity of the observed individual; species = species affiliation (F. neophytus or G. cauerensis); video =  video ID; treatment = configuration tested; feed = number of bites taken over the duration of the observations (30 minutes); before_after = before or after generic food addition -- only before data are used for this paper. All videos, labelled by their respective trial, are accessible under the following link: https://www.youtube.com/playlist?list=PL9LfYSgK5itOtyll0jJr7Kszdf6olw6Ce 


All code written by Simon J. Brandl (simonjbrandl@gmail.com and https://github.com/simonjbrandl).